// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmQzskiwBHuebwM0xDEm7ccdA6V_lTo24',
    appId: '1:83546488630:web:69d4d2725a97d92a443d97',
    messagingSenderId: '83546488630',
    projectId: 'informasi-65ba3',
    authDomain: 'informasi-65ba3.firebaseapp.com',
    storageBucket: 'informasi-65ba3.appspot.com',
    measurementId: 'G-S3RN5CZ1PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuZIeDcqonhYMBv47gfZTNFjha5LAawGI',
    appId: '1:83546488630:android:4d86ff8bb2589452443d97',
    messagingSenderId: '83546488630',
    projectId: 'informasi-65ba3',
    storageBucket: 'informasi-65ba3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSbt24ahWbVUMcNIbNFfRaLjbKEvoTw4U',
    appId: '1:83546488630:ios:faad6f87774b0fda443d97',
    messagingSenderId: '83546488630',
    projectId: 'informasi-65ba3',
    storageBucket: 'informasi-65ba3.appspot.com',
    iosBundleId: 'com.example.info',
  );
}
